### ISSUE TITLE
PHP Warning:  Missing argument 3 for BadgeosShowSub_Plugin::addLinkToSubmission()

### ISSUE THREAD

**Issue by mediaformat** [DigitalPygmalion/badge-factor-showsubmission-addon#1]
`PHP Warning:  Missing argument 3 for BadgeosShowSub_Plugin::addLinkToSubmission() in /plugins/badge-factor-showsubmission-addon/BadgeosShowSub_Plugin.php on line 83`

**Comment by danidou** [comment]
Fixed by removing the third, unused method parameter "$mode", and by fixing the add_filter call in addActionsAndFilters() accordingly.
